name: Laravel CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest  # This can be changed to a self-hosted runner, e.g., 'self-hosted'

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update
    - name: Generate Key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

  deploy:
    runs-on: self-hosted  # Use your own GitHub runner here (self-hosted)

    needs: laravel-tests  # Ensures deployment only happens after tests are successful
    steps:
    - uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Deploy Application
      run: |
        echo "Starting deployment process"
        cd /path/to/your/application || exit 1  # Path to your deployment directory on the self-hosted runner
        git pull origin main || exit 1
        composer install --no-dev --prefer-dist || exit 1  # Install production dependencies
        php artisan migrate --force || exit 1  # Run migrations
        php artisan config:cache || exit 1  # Clear and cache config
        php artisan route:cache || exit 1  # Cache routes
        php artisan view:cache || exit 1  # Cache views
        echo "Deployment successful!"
